# dbt_project.yml

name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  my_new_project:
    # This applies to all models under models/staging/
    +persist_docs:
      relation: true    # This persists table/view descriptions
      columns: true     # This persists column descriptions
    staging:
      +schema:  # This ensures the staging models are stored in the 'DBT_BYUKSEL' schema
      +materialized: view  # You can change this to 'table' if you want staging models as tables
    marts:
      +schema:
      +materialized: table

    # Default configurations for other folders, if necessary
    example:
      +materialized: table  # Can change for other folders if needed
