version: 2
sources:
  - name: raw  # Schema where the raw tables are located in your Snowflake database
    database: SUMUP_CASE  # Replace with your actual Snowflake database name
    schema: RAW  # Replace with your raw schema
    tables:
      - name: WEB_ORDERS  # Raw web orders table
        description: "Raw web orders data"
      - name: CHANNELS  # Raw channels table
        description: "Raw channels data"
      - name: LEADS_FUNNEL  # Raw leads funnel table
        description: "Raw leads funnel data"
