-- models/staging/stg_leads_funnel.sql

with raw_leads_funnel as (
    select
        DATE,
        CURRENCY,
        COUNTRY_CODE,
        CAMPAIGN_ID,
        CAMPAIGN_NAME,
        PRODUCT,
        CHANNEL_3,
        CHANNEL_4,
        CHANNEL_5,
        TOTAL_IMPRESSIONS,
        TOTAL_CLICKS,
        TOTAL_SPEND,
        TOTAL_LEADS,
        TOTAL_FAKE_LEADS,
        TOTAL_SQLS,
        TOTAL_MEETING_DONE,
        TOTAL_SIGNED_LEADS,
        TOTAL_POS_LITE_DEALS
    from {{ source('DBT_BYUKSEL', 'LEADS_FUNNEL') }}
)

select
    -- Dates
    DATE as LEAD_DATE,

    -- Textual metadata cleaned and uppercased
    COALESCE(UPPER(TRIM(CURRENCY)), 'UNKNOWN_CURRENCY') as CURRENCY,
    COALESCE(UPPER(TRIM(COUNTRY_CODE)), 'UNKNOWN_COUNTRY') as COUNTRY_CODE,
    COALESCE(
        UPPER(TRIM(REGEXP_REPLACE(CAMPAIGN_ID, '\.\d+$', ''))),
        'UNKNOWN_CAMPAIGN'
    ) as CAMPAIGN_ID,
    COALESCE(UPPER(TRIM(CAMPAIGN_NAME)), 'UNKNOWN_CAMPAIGN_NAME') as CAMPAIGN_NAME,
    COALESCE(UPPER(TRIM(PRODUCT)), 'UNKNOWN_PRODUCT') as PRODUCT,
    COALESCE(UPPER(TRIM(CHANNEL_3)), 'UNKNOWN_CHANNEL_3') as CHANNEL_3,
    COALESCE(UPPER(TRIM(CHANNEL_4)), 'UNKNOWN_CHANNEL_4') as CHANNEL_4,
    COALESCE(UPPER(TRIM(CHANNEL_5)), 'UNKNOWN_CHANNEL_5') as CHANNEL_5,

    -- Numeric metrics with COALESCE and casting
    COALESCE(TOTAL_IMPRESSIONS, 0)::INT as TOTAL_IMPRESSIONS,
    COALESCE(TOTAL_CLICKS, 0)::INT as TOTAL_CLICKS,
    COALESCE(TOTAL_SPEND, 0)::FLOAT as TOTAL_SPEND,
    COALESCE(TOTAL_LEADS, 0)::INT as TOTAL_LEADS,
    COALESCE(TOTAL_FAKE_LEADS, 0)::INT as TOTAL_FAKE_LEADS,
    COALESCE(TOTAL_SQLS, 0)::INT as TOTAL_SQLS,
    COALESCE(TOTAL_MEETING_DONE, 0)::INT as TOTAL_MEETING_DONE,
    COALESCE(TOTAL_SIGNED_LEADS, 0)::INT as TOTAL_SIGNED_LEADS,
    COALESCE(TOTAL_POS_LITE_DEALS, 0)::INT as TOTAL_POS_LITE_DEALS

from raw_leads_funnel
